<?php  if ( ! defined('BASEPATH')) exit('No direct script access allowed');

$config['url'] = array(
                    1 => 'Sequoia',
                    3  => array('usatech/copy', 'usatech/laundry', 'usatech/vending'),
                    5  => 'itc_papercut',
                    7  =>  'micros *',
                    15  =>  'studentlink',
                    17  =>  'follett',
                    19  =>  'pharos',
                    29  =>  'itc *',
                    31 =>  'itc *',
                    31  =>  'itc *',
                    36  =>  array('apriva_web/json', 'apriva_web/xml'),
                    39 =>  'planet',
                    44 =>  array('dishout/json', 'dishout/xml'),
                    45 =>  'itc_activity',
                    46 =>  array('tapingo/json', 'tapingo/xml'),                
                    47 =>  array('prism/json', 'prism/xml'), 
                    48 =>  'itc *',               
                    49 =>  'itc *',              
                    50 =>  'itc *',              
                    52 =>  'raspberrypi/json',              
                    53 =>  'itc_goprint',              
                    55 =>  array('castle/json', 'castle/xml'),  
                    56 =>  array('jamex/json', 'jamex/xml'),                     
                    57 =>  array('wepa/json', 'wepa/xml'),                     
                    59 =>  array('infor/json', 'infor/xml'),
                    60 =>  'mbsbooks *',
                    63 => 'clover/json',
                    67 =>'ncr_aloha/json',
                    71 =>'earnwallet/json',
                    72 =>'vengo/json',
                    73 =>'hangry/json',
                    74 =>  array('rutgers_papercut/json', 'rutgers_papercut/xml'),
                    75 => 'universitytickets/json',
                    76 => 'speed_queen_insights/json',
                    77 => 'ratexbookstore/json',
                    85 =>  array('alliancels/json', 'alliancels/xml'),
                    86 =>'pcounter/json',
                    88 =>'',
                    89 =>'starship/json',
                    90 =>'campuscard/json',
                    91 =>'agilysys/json',
                    92 =>'flowbird/json',
                    96 =>'compassdigital/json',
                    97 =>'ecampus/json',
                    98 =>'itc_meal',
                    100 =>'universityrecrentals/json',
                    101 =>'catapult/json',
                    102 =>'canon/json',
                    104 =>'csc_digital_insights/json',
                    105 =>'bite/json',
                    106 =>'gooduncle/json',
                    107 =>'boost/json',
                    108 =>'cafebonapp/json',
                    109 =>'pax/json',
                    );


                  
